<?php

namespace ZeeshanMushtaq\ApiNexa\Documentation;

use ZeeshanMushtaq\ApiNexa\Support\EndpointDescriptor;
use ZeeshanMushtaq\ApiNexa\Support\RegistrySnapshot;

class HtmlGenerator
{
    public function generate(RegistrySnapshot $registry): string
    {
        $title = htmlspecialchars((string) config('apinexa.documentation.title', 'API Documentation'), ENT_QUOTES, 'UTF-8');
        $endpoints = array_values($registry->endpoints);

        usort($endpoints, fn(EndpointDescriptor $a, EndpointDescriptor $b) => [$a->endpoint, $a->method] <=> [$b->endpoint, $b->method]);

        $cards = '';

        foreach ($endpoints as $endpoint) {
            $cards .= $this->renderEndpoint($endpoint);
        }

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{$title}</title>
    <style>
        :root { color-scheme: light dark; font-family: ui-sans-serif, system-ui, sans-serif; }
        body { margin: 0; background: #0f172a; color: #e2e8f0; }
        header { padding: 2rem; background: linear-gradient(135deg, #1d4ed8, #7c3aed); }
        h1 { margin: 0 0 .5rem; }
        main { max-width: 960px; margin: 0 auto; padding: 2rem 1rem 4rem; }
        .endpoint { background: #1e293b; border: 1px solid #334155; border-radius: .75rem; padding: 1.25rem; margin-bottom: 1rem; }
        .method { display: inline-block; font-weight: 700; font-size: .75rem; letter-spacing: .05em; padding: .25rem .5rem; border-radius: .375rem; margin-right: .5rem; }
        .GET { background: #065f46; color: #d1fae5; }
        .POST { background: #1e40af; color: #dbeafe; }
        .PUT, .PATCH { background: #92400e; color: #fef3c7; }
        .DELETE { background: #991b1b; color: #fee2e2; }
        .path { font-family: ui-monospace, monospace; font-size: 1rem; }
        .meta { margin-top: .75rem; color: #94a3b8; font-size: .875rem; }
        .payload { margin-top: 1rem; }
        pre { background: #0f172a; padding: 1rem; border-radius: .5rem; overflow-x: auto; font-size: .8125rem; }
        .badge { display: inline-block; background: #334155; padding: .125rem .5rem; border-radius: 999px; margin: .125rem .25rem 0 0; font-size: .75rem; }
    </style>
</head>
<body>
    <header>
        <h1>{$title}</h1>
        <p>Generated by APINEXA · {$registry->count()} endpoint(s)</p>
    </header>
    <main>
        {$cards}
    </main>
</body>
</html>
HTML;
    }

    protected function renderEndpoint(EndpointDescriptor $endpoint): string
    {
        $name = htmlspecialchars($endpoint->name, ENT_QUOTES, 'UTF-8');
        $method = htmlspecialchars($endpoint->method, ENT_QUOTES, 'UTF-8');
        $path = htmlspecialchars($endpoint->endpoint, ENT_QUOTES, 'UTF-8');
        $version = htmlspecialchars($endpoint->version, ENT_QUOTES, 'UTF-8');
        $auth = $endpoint->auth ? 'Required' : 'None';
        $description = $endpoint->description
            ? '<p>' . htmlspecialchars($endpoint->description, ENT_QUOTES, 'UTF-8') . '</p>'
            : '';

        $roles = '';
        foreach ($endpoint->roles as $role) {
            $roles .= '<span class="badge">' . htmlspecialchars((string) $role, ENT_QUOTES, 'UTF-8') . '</span>';
        }

        $scopes = '';
        foreach ($endpoint->scopes as $scope) {
            $scopes .= '<span class="badge">' . htmlspecialchars((string) $scope, ENT_QUOTES, 'UTF-8') . '</span>';
        }

        $payloadBlock = '';
        if ($endpoint->payload !== []) {
            $json = htmlspecialchars(
                json_encode($endpoint->payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES),
                ENT_QUOTES,
                'UTF-8'
            );
            $payloadBlock = <<<HTML
            <div class="payload">
                <strong>Payload rules</strong>
                <pre>{$json}</pre>
            </div>
            HTML;
        }

        $rolesBlock = $roles !== '' ? "<div class=\"meta\">Roles: {$roles}</div>" : '';
        $scopesBlock = $scopes !== '' ? "<div class=\"meta\">Scopes: {$scopes}</div>" : '';

        return <<<HTML
        <article class="endpoint">
            <div>
                <span class="method {$method}">{$method}</span>
                <span class="path">{$path}</span>
            </div>
            <h2>{$name}</h2>
            {$description}
            <div class="meta">Version: {$version} · Auth: {$auth}</div>
            {$rolesBlock}
            {$scopesBlock}
            {$payloadBlock}
        </article>
        HTML;
    }
}

