<?php

namespace ZeeshanMushtaq\ApiNexa\Documentation;

use ZeeshanMushtaq\ApiNexa\Support\EndpointDescriptor;
use ZeeshanMushtaq\ApiNexa\Support\RegistrySnapshot;
use ZeeshanMushtaq\ApiNexa\Support\ValidationRuleParser;

class OpenApiGenerator
{
    /**
     * @return array<string, mixed>
     */
    public function generate(RegistrySnapshot $registry): array
    {
        $paths = [];

        foreach ($registry->endpoints as $endpoint) {
            $paths = $this->mergePath($paths, $endpoint);
        }

        return [
            'openapi' => '3.1.0',
            'info' => [
                'title' => (string) config('apinexa.documentation.title', 'API Documentation'),
                'version' => (string) config('apinexa.documentation.version', '1.0.0'),
                'description' => 'Generated by APINEXA',
            ],
            'paths' => $paths,
            'components' => [
                'securitySchemes' => [
                    'ApiKeyAuth' => [
                        'type' => 'apiKey',
                        'in' => 'header',
                        'name' => (string) config('apinexa.keys.header', 'X-Api-Key'),
                    ],
                ],
            ],
        ];
    }

    /**
     * @param  array<string, mixed>  $paths
     * @return array<string, mixed>
     */
    protected function mergePath(array $paths, EndpointDescriptor $endpoint): array
    {
        $uri = $endpoint->endpoint;
        $method = strtolower($endpoint->method);

        $operation = [
            'operationId' => $this->operationId($endpoint),
            'summary' => $endpoint->name,
            'description' => $endpoint->description,
            'tags' => [$endpoint->version],
            'responses' => [
                '200' => [
                    'description' => 'Successful response',
                ],
            ],
            'x-APINEXA-roles' => $endpoint->roles,
            'x-APINEXA-scopes' => $endpoint->scopes,
        ];

        if ($endpoint->auth) {
            $operation['security'] = [['ApiKeyAuth' => []]];
        }

        if ($endpoint->payload !== []) {
            $properties = [];
            $required = ValidationRuleParser::requiredFields($endpoint->payload);

            foreach ($endpoint->payload as $field => $rules) {
                $properties[$field] = ValidationRuleParser::toOpenApiProperty((string) $rules);
            }

            $operation['requestBody'] = [
                'required' => $required !== [],
                'content' => [
                    'application/json' => [
                        'schema' => [
                            'type' => 'object',
                            'properties' => $properties,
                            'required' => $required,
                        ],
                    ],
                ],
            ];
        }

        $paths[$uri] ??= [];
        $paths[$uri][$method] = array_filter($operation, fn ($value) => $value !== null && $value !== []);

        return $paths;
    }

    protected function operationId(EndpointDescriptor $endpoint): string
    {
        $slug = preg_replace('/[^a-zA-Z0-9_]+/', '_', strtolower($endpoint->name)) ?: 'endpoint';

        return trim($slug, '_').'_'.strtolower($endpoint->method);
    }
}

